micronaut:
  application:
    name: pix
datasources:
  default:
    url: jdbc:mysql://localhost:3307/db_keyManager_teste?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSl=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
